# updated to include examples of text_layer, panning_layer, group_layer, and markup_layer
Sequence:
    - LastScores:
        Font: status
        FontStyle: 
            interior_color: [130,230,130]
            line_width: 1
            line_color: [60,60,60]
        Background: major-eyes-o_bg
        # lampshow: attract_show_2
        # sound: sling
        duration: 2.0
    - Combo:
        Text:
            - "Ed Owens"
            - ""
            - "Presents"
        # Font: med  -- these are optional for 
        # FontStyle: weird  -- Combo layers
        Animation: section9_bg
        # lampshow: attract_show_2
        # sound: sling
        duration: 1.5
    - Combo:
        Animation: titlescreen
        # lampshow: attract_show_2
        duration: 2.5
    - Combo:
        Animation: MGC
        duration: 2.5
    - Combo:
        Animation: DeadFlip
        duration: 2.5
    - text_layer: # a more powerful version of the Combo Layer for text
        x: .50   # 50% of the display width
        y: .50    # 50% of the display height
        h_justify: center
        v_justify: center
        Text: "PRESS START"        
        Font: status
        duration: 1.0
    - Combo:
        Animation: Skeleton
        duration: 2.5
    - HighScores:
        Font: status
        FontStyle: 
            interior_color: [130,230,130]
            line_width: 1
            line_color: [60,60,60]
        Background: crew_bg
        Order:
            - player
            - category
            - score
        duration: 3.0 # increase duration since it is now the length of all high score frames, together!
    - Combo:
        Animation: PinballMayhem
        duration: 2.5