# P-ROC Game Description file for Judge Dredd
PRGame:
    machineType: pdb
    numBalls: 4
PRFlippers:
    - flipperLwR
    - flipperLwL
    - flipperUpR
PRBumpers:
    - slingL
    - slingR
    - jetB
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #                  'NC' (normally closed.  Common for optos)
    flipperLwL:
        number: 8
        ballsearch: stop
    flipperLwR:
        number: 9
        ballsearch: stop
    flipperUpR:
        number: 10
        ballsearch: stop
    startButton:
        number: 11
    tilt:
        number: 12
    coinDoor:
        number: 13
    ticket:
        number: 14
    coinL:
        number: 0
    coinR:
        number: 1
    exit:
        number: 2
    down:
        number: 3
    up:
        number: 4
    enter:
        number: 5
    slamTilt:
        number: 6
    trough1:
        number: 16
        ballsearch: reset
    trough2:
        number: 17
        ballsearch: reset
    trough3:
        number: 18
        ballsearch: reset
    shooter:
        number: 19
        ballsearch: stop, reset
    trough4:
        number: 20
        type: NC
        ballsearch: reset
    throughJam:
        number: 21
        type: NC
        ballsearch: reset
        tags: troughJam,tilt_visible
    StandUpL:
        number: 24
        ballsearch: reset
    StandUpR:
        number: 25
        ballsearch: reset
    outlaneL:
        number: 26
        ballsearch: reset
    inlaneL:
        number: 27
        ballsearch: reset
    slingL:
        number: 28
        ballsearch: reset
    slingR:
        number: 29
        ballsearch: reset
    inlaneR:
        number: 30
        ballsearch: reset
    outlaneR:
        number: 31
        ballsearch: reset
    ScoopL:
        number: 72
        type: NC
        ballsearch: stop
    rampLeftLow:
        number: 73
        ballsearch: reset
    StandUpRamp:
        number: 74
        ballsearch: reset
    StandUp2:
        number: 75
        ballsearch: reset
    StandUp5:
        number: 76
        ballsearch: reset
    StandUp0:
        number: 77
        ballsearch: reset
    StandUp1:
        number: 78
        ballsearch: reset
    ScoopR:
        number: 79
        type: NC
        ballsearch: stop
    jetB:
        number: 48
        ballsearch: reset
    laneL:
        number: 49
        ballsearch: reset
    laneC:
        number: 50
        ballsearch: reset
    laneR:
        number: 51
        ballsearch: reset
    orbit:
        number: 52
        ballsearch: reset
    rampLeftHigh:
        number: 53
        ballsearch: reset
    StandUpSpinner:
        number: 54
        ballsearch: reset
    spinner:
        number: 55
        ballsearch: reset
    dropG:
        number: 57
        ballsearch: reset
    dropH:
        number: 58
        ballsearch: reset
    dropO:
        number: 59
        ballsearch: reset
    dropS:
        number: 60
        ballsearch: reset
    dropT:
        number: 61
        ballsearch: reset
    dropMiss:
        number: 62
        ballsearch: reset
    lock1:
        number: 64
        type: NC
        ballsearch: stop
    lock2:
        number: 65
        type: NC
        ballsearch: stop
    lock3:
        number: 66
        ballsearch: stop
    rampRight:
        number: 67
        ballsearch: reset
    lockBashL:
        number: 69
        ballsearch: reset
    lockBashR:
        number: 70
        ballsearch: reset
    upexit:
        number: 68
        ballsearch: reset
    thermoOC:
        number: 71
        type: NC
        ballsearch: reset
PRCoils:
    flipperLwRMain:
        number: A0-B0-0
    flipperLwRHold:
        number: A0-B0-1
    slingR:
        number: A0-B0-2
    trough:
        number: A0-B0-3
    plunger:
        number: A0-B0-4
        tags: autoPlunger
    flipperUpRMain:
        number: A0-B1-0
    flipperUpRHold:
        number: A0-B1-1
    gate:
        number: A0-B1-2
        ballsearch: True
    scoopR:
        number: A0-B1-3
        ballsearch: True
    droptarget:
        number: A0-B1-4
        ballsearch: True
    lockdrop:
        number: A0-B1-5
    jetB:
        number: A0-B1-6
        ballsearch: True
    flasherscoopL:
        number: A1-B0-0
    flasherscoopR:
        number: A1-B0-1
    flasherramp:
        number: A1-B0-2
    flasherlock:
        number: A1-B0-3
    giLighting:
        number: A1-B0-4
    backboxR:
        number: A1-B0-5
    backboxG:
        number: A1-B0-6
    backboxB:
        number: A1-B0-7
    flipperLwLMain:
        number: A1-B1-0
    flipperLwLHold:
        number: A1-B1-1
    slingL:
        number: A1-B1-2
    scoopL:
        number: A1-B1-3
        ballsearch: True
    knocker:
        number: A1-B1-6
    shaker:
        number: A1-B1-7  #not present future use
PRLamps:
    startButton:
        number: A3-R83
        polarity: False
    perp1W:
        number: L11
    perp1R:
        number: L12
    perp1Y:
        number: L13
    perp1G:
        number: L14
    perp2W:
        number: L15
    perp2R:
        number: L16
    perp2Y:
        number: L17
    perp2G:
        number: L18
    perp4W:
        number: L21
    perp4R:
        number: L22
    perp4Y:
        number: L23
    perp4G:
        number: L24
    perp5W:
        number: L25
    perp5R:
        number: L26
    perp5Y:
        number: L27
    perp5G:
        number: L28
    perp3W:
        number: L31
    perp3R:
        number: L32
    perp3Y:
        number: L33
    perp3G:
        number: L34
    lock1:
        number: L35
    lock2:
        number: L36
    lock3:
        number: L37
    superGame:
        number: L38
    crimeLevel4:
        number: L41
    crimeLevel3:
        number: L42
    crimeLevel2:
        number: L43
    crimeLevel1:
        number: L44
    meltdown:
        number: L45
    impersonator:
        number: L46
    battleTank:
        number: L47
    stopMeltdown:
        number: L48
    stakeout:
        number: L51
    safecracker:
        number: L52
    pursuit:
        number: L53
    ultChallenge:
        number: L54
    manhunt:
        number: L55
    blackout:
        number: L56
    sniper:
        number: L57
    pickAPrize:
        number: L58
    extraBall2:
        number: L61
    rightStartFeature:
        number: L62
    tankCenter:
        number: L63
    awardSniper:
        number: L64
    airRade:
        number: L65
    leftCenterFeature:
        number: L66
    tankLeft:
        number: L67
    mystery:
        number: L68
    dropTargetJ:
        number: L71
    dropTargetU:
        number: L72
    dropTargetD:
        number: L73
    dropTargetG:
        number: L74
    dropTargetE:
        number: L75
    awardSafecracker:
        number: L76
    multiballJackpot:
        number: L77
    awardBadImpersonator:
        number: L78
    awardStakeout:
        number: L81
    blackoutJackpot:
        number: L82
    drainShield:
        number: L83
        tags: shoot_again
    judgeAgain:
        number: L84
    advanceCrimeLevel:
        number: L85
    tankRight:
        number: L86
    buyIn:
        number: L87
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05
