# P-ROC Game Description file for Judge Dredd
PRGame:
    machineType: pdb
    numBalls: 4
PRFlippers:
    - flipperLwR
    - flipperLwL
    - flipperUpR
PRBumpers:
    - slingL
    - slingR
    - jetB
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #                  'NC' (normally closed.  Common for optos)
    flipperLwR:
        number: 23
        ballsearch: stop # stop: this switch prevents the ballsearch timer from even starting
    flipperLwL: 
        number: 22
        ballsearch: stop 
    flipperUpR: 
        number: 20
        ballsearch: stop 
    coinL:
        number: 64 #not present
    coinR:
        number: 64 #not present
    exit: 
        number: 64 #not present
    down: 
        number: 64 #not present
    up: 
        number: 64 #not present
    enter: 
        number: 64 #not present
    startButton:
        number: 21
    tilt:
        number: 64 #not present
    slamTilt:
        number: 64 #not present
    coinDoor:
        number: 64 #not present
    ticket:
        number: 64 #not present
    trough1:
        number: 8
        ballsearch: reset # reset: this switch resets a ballsearch timer to occur X-seconds after this was seen
    trough2:
        number: 9
        ballsearch: reset 
    trough3:
        number: 10
        ballsearch: reset 
    trough4:
        number: 6
        type: NC
        ballsearch: reset 
    throughJam:
        number: 7
        type: NC
        ballsearch: reset 
    shooter:
        number: 11
        ballsearch: stop, reset
    jetB:
        number: 24
        ballsearch: reset 
    slingL:
        number: 0
        ballsearch: reset 
    slingR:
        number: 1
        ballsearch: reset 
    StandUpL: #need to rename left of left scoop Left
        number: 4
        ballsearch: reset 
    StandUpR: #need to rename left of left scoop Right
        number: 3
        ballsearch: reset 
    ScoopL:
        number: 2
        type: NC
        ballsearch: stop
    ScoopR:
        number: 5
        type: NC
        ballsearch: stop
    outlaneL:
        number: 64 #not present
        ballsearch: reset 
    inlaneL:
        number: 64 #not present
        ballsearch: reset 
    inlaneR:
        number: 64 #not present        
        ballsearch: reset 
    outlaneR:
        number: 64 #not present
        ballsearch: reset 
    StandUp2:
        number: 31
        ballsearch: reset 
    StandUp5:
        number: 17
        ballsearch: reset 
    StandUp0:
        number: 18
        ballsearch: reset 
    StandUp1:
        number: 19
        ballsearch: reset 
    dropG:
        number: 25
        ballsearch: reset 
    dropH:
        number: 26
        ballsearch: reset 
    dropO:
        number: 27
        ballsearch: reset 
    dropS:
        number: 28
        ballsearch: reset 
    dropT:
        number: 29
        ballsearch: reset 
    dropMiss:  #Rubber band switch behind drop targets
        number: 30  
        ballsearch: reset 
    spinner:
        number: 15
        ballsearch: reset 
    rampLeftLow:
        number: 12 
        ballsearch: reset 
    rampLeftHigh:
        number: 13
        ballsearch: reset 
    rampRight:
        number: 14
        ballsearch: reset 
    laneL:
        number: 64 #not present
        ballsearch: reset 
    laneC:
        number: 64 #not present
        ballsearch: reset 
    laneR:
        number: 64 #not present
        ballsearch: reset 
    orbitRLow:
        number: 64 #not present
        ballsearch: reset 
    orbitRHigh:
        number: 64 #not present
        ballsearch: reset 
    lock1:
        number: 64 #not present
        ballsearch: reset 
    lock2:
        number: 64 #not present
        ballsearch: reset
    lock3:
        number: 64 #not present
        ballsearch: reset
    thermoOC:
        number: 16
        ballsearch: reset
    lockBashL:
        number: 64 #not present
        ballsearch: reset
    lockBashR:
        number: 64 #not64resent
        ballsearch: reset
PRCoils:
    flipperLwRMain: 
        number: A0-B0-4
    flipperLwRHold: 
        number: A0-B0-5
    flipperLwLMain: 
        number: A0-B0-7
    flipperLwLHold: 
        number: A0-B0-6
    flipperUpRMain: 
        number: A0-B1-7
    flipperUpRHold: 
        number: A0-B1-6
    trough:
        number: A0-B1-2
    slingR:
        number: A0-B0-2
    slingL:
        number: A0-B0-3
    scoopL:
        number: A0-B0-1
        ballsearch: True
    scoopR:
        number: A0-B0-0
        ballsearch: True
    plunger:
        number: A0-B1-4 #not present
        tags: autoPlunger # add this tag to support autoplunging on ball save
    knocker:
        number: A0-B1-4 #not present
    jetB:
        number: A0-B1-1
        ballsearch: True
    droptarget:
        number: A0-B1-0
    flasher1:
        number: A0-B1-4 #not present
    flasher2:
        number: A0-B1-4 #not present
    flasher3:
        number: A0-B1-4 #not present
    flasher4:
        number: A0-B1-4 #not present
    flasher5:
        number: A0-B1-4 #not present
    flasher6:
        number: A0-B1-4 #not present
    flasher7:
        number: A0-B1-4 #not present
    flasher8:
        number: A0-B1-4 #not present
PRLamps:
    perp1W:
        number: L11
    perp1R:
        number: L12
    perp1Y:
        number: L13
    perp1G:
        number: L14
    perp2W:
        number: L15
    perp2R:
        number: L16
    perp2Y:
        number: L17
    perp2G:
        number: L18
    perp4W:
        number: L21
    perp4R:
        number: L22
    perp4Y:
        number: L23
    perp4G:
        number: L24
    perp5W:
        number: L25
    perp5R:
        number: L26
    perp5Y:
        number: L27
    perp5G:
        number: L28
    perp3W:
        number: L31
    perp3R:
        number: L32
    perp3Y:
        number: L33
    perp3G:
        number: L34
    lock1:
        number: L35
    lock2:
        number: L36
    lock3:
        number: L37
    superGame:
        number: L38
    crimeLevel4:
        number: L41
    crimeLevel3:
        number: L42
    crimeLevel2:
        number: L43
    crimeLevel1:
        number: L44
    meltdown:
        number: L45
    impersonator:
        number: L46
    battleTank:
        number: L47
    stopMeltdown:
        number: L48
    stakeout:
        number: L51
    safecracker:
        number: L52
    pursuit:
        number: L53
    ultChallenge:
        number: L54
    manhunt:
        number: L55
    blackout:
        number: L56
    sniper:
        number: L57
    pickAPrize:
        number: L58
    extraBall2:
        number: L61
    rightStartFeature:
        number: L62
    tankCenter:
        number: L63
    awardSniper:
        number: L64
    airRade:
        number: L65
    leftCenterFeature:
        number: L66
    tankLeft:
        number: L67
    mystery:
        number: L68
    dropTargetJ:
        number: L71
    dropTargetU:
        number: L72
    dropTargetD:
        number: L73
    dropTargetG:
        number: L74
    dropTargetE:
        number: L75
    awardSafecracker:
        number: L76
    multiballJackpot:
        number: L77
    awardBadImpersonator:
        number: L78
    awardStakeout:
        number: L81
    blackoutJackpot:
        number: L82
    drainShield:
        number: L83
        tags: shoot_again
    judgeAgain:
        number: L84
    advanceCrimeLevel:
        number: L85
    tankRight:
        number: L86
    buyIn:
        number: L87
    startButton:
        number: L88
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05
